### ISSUE TITLE
不支持容器方式启动吗

### ISSUE THREAD

**Issue by Jasmine456** [oula-network/aleo#3]
使用docker启动后报错

2024-08-27T09:25:03.186457Z  INFO aleo_prover::client: Prover start
2024-08-27T09:25:03.373372Z  INFO aleo_prover::rest: rest server start in 0.0.0.0:9988
2024-08-27T09:25:03.376739Z  INFO aleo_prover::dataholder: 
+------------------------------------------------------------------------+
|                                  OULA                                  |
+========================================================================+
|  GPU     | ProofRate            | Valid | Power | Memory | Device      |
| ---------+----------------------+-------+-------+--------+------------ |
|  Total   | 0                    | 0     |       |        | Uptime  0s  |
|  Version | 1244c11-2024-08-26-1 |       |       |        |             |
+------------------------------------------------------------------------+

2024-08-27T09:25:03.458269Z ERROR aleo_pool_core::net_monitor: gen metrics error: No such file or directory (os error 2)
2024-08-27T09:25:03.458377Z  INFO aleo_prover::client: Network delay: 9999.99ms, loss: 999999.0%
2024-08-27T09:25:03.716662Z  INFO aleo_prover::prover::gpu: working device gpu_num=5
2024-08-27T09:25:03.717425Z  INFO GPU{gpu_index=0}: aleo_prover::prover::gpu: reseting gpu
2024-08-27T09:25:03.717968Z  INFO GPU{gpu_index=2}: aleo_prover::prover::gpu: reseting gpu
2024-08-27T09:25:03.722099Z  INFO GPU{gpu_index=3}: aleo_prover::prover::gpu: reseting gpu
2024-08-27T09:25:03.724067Z  INFO aleo_prover::client: Connecting to server: wss://aleo.oula.network:6666
2024-08-27T09:25:03.724654Z  INFO GPU{gpu_index=1}: aleo_prover::prover::gpu: reseting gpu
2024-08-27T09:25:03.728031Z  INFO GPU{gpu_index=4}: aleo_prover::prover::gpu: reseting gpu
2024-08-27T09:25:04.548322Z  INFO aleo_prover::client: Sending auth request: AuthRequest { username: "xxx", metadata: Object {"machine_name": String("41922ca5cd10"), "version": Number(1.0)} }
2024-08-27T09:25:05.168625Z  INFO aleo_prover::client: Run for pool mode
2024-08-27T09:25:05.169120Z  INFO aleo_prover::client: Received new task task.difficulty=90000000 current_epoch=1599
2024-08-27T09:25:05.545922Z  INFO GPU{gpu_index=0}: aleo_prover::prover::gpu: initializing prover
2024-08-27T09:25:05.555534Z  INFO GPU{gpu_index=0}: aleo_prover::prover::gpu: waiting for tasks
2024-08-27T09:25:05.630908Z  INFO GPU{gpu_index=4}: aleo_prover::prover::gpu: initializing prover
2024-08-27T09:25:05.659633Z  INFO GPU{gpu_index=3}: aleo_prover::prover::gpu: initializing prover
2024-08-27T09:25:05.735503Z  INFO GPU{gpu_index=1}: aleo_prover::prover::gpu: initializing prover
2024-08-27T09:25:05.737346Z  INFO GPU{gpu_index=2}: aleo_prover::prover::gpu: initializing prover
2024-08-27T09:25:05.744980Z  INFO GPU{gpu_index=4}: aleo_prover::prover::gpu: waiting for tasks
2024-08-27T09:25:05.747946Z  INFO GPU{gpu_index=3}: aleo_prover::prover::gpu: waiting for tasks
2024-08-27T09:25:05.763447Z  INFO GPU{gpu_index=1}: aleo_prover::prover::gpu: waiting for tasks
2024-08-27T09:25:05.764755Z  INFO GPU{gpu_index=2}: aleo_prover::prover::gpu: waiting for tasks
2024-08-27T09:26:03.378026Z  INFO aleo_prover::dataholder: 
+-------------------------------------------------------------------------+
|                                  OULA                                   |
+=========================================================================+
|  GPU     | ProofRate            | Valid | Power | Memory | Device       |
| ---------+----------------------+-------+-------+--------+------------- |
|  Total   | 0                    | 0     |       |        | Uptime  60s  |
|  Version | 1244c11-2024-08-26-1 |       |       |        |              |
+-------------------------------------------------------------------------+

2024-08-27T09:27:03.379775Z  INFO aleo_prover::dataholder: 
+--------------------------------------------------------------------------+
|                                   OULA                                   |
+==========================================================================+
|  GPU     | ProofRate            | Valid | Power | Memory | Device        |
| ---------+----------------------+-------+-------+--------+-------------- |
|  Total   | 0                    | 0     |       |        | Uptime  120s  |
|  Version | 1244c11-2024-08-26-1 |       |       |        |               |
+--------------------------------------------------------------------------+

2024-08-27T09:28:03.381493Z  INFO aleo_prover::dataholder: 
+--------------------------------------------------------------------------+
|                                   OULA                                   |
+==========================================================================+
|  GPU     | ProofRate            | Valid | Power | Memory | Device        |
| ---------+----------------------+-------+-------+--------+-------------- |
|  Total   | 0                    | 0     |       |        | Uptime  180s  |
|  Version | 1244c11-2024-08-26-1 |       |       |        |               |
+--------------------------------------------------------------------------+

2024-08-27T09:28:13.700908Z  INFO GPU{gpu_index=0}: aleo_prover::prover::gpu: new task received epoch=1599 proof_target=90000000
thread '<unnamed>' panicked at aleo-pool-prover/src/dataholder.rs:294:17:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-08-27T09:28:27.023991Z  INFO GPU{gpu_index=4}: aleo_prover::prover::gpu: new task received epoch=1599 proof_target=90000000
thread '<unnamed>' panicked at aleo-pool-prover/src/dataholder.rs:294:17:
index out of bounds: the len is 0 but the index is 4
2024-08-27T09:28:29.021062Z  INFO GPU{gpu_index=2}: aleo_prover::prover::gpu: new task received epoch=1599 proof_target=90000000
thread '<unnamed>' panicked at aleo-pool-prover/src/dataholder.rs:294:17:
index out of bounds: the len is 0 but the index is 2
2024-08-27T09:28:30.877486Z  INFO GPU{gpu_index=1}: aleo_prover::prover::gpu: new task received epoch=1599 proof_target=90000000
thread '<unnamed>' panicked at aleo-pool-prover/src/dataholder.rs:294:17:
index out of bounds: the len is 0 but the index is 1
2024-08-27T09:28:36.372830Z  INFO GPU{gpu_index=3}: aleo_prover::prover::gpu: new task received epoch=1599 proof_target=90000000
thread '<unnamed>' panicked at aleo-pool-prover/src/dataholder.rs:294:17:
index out of bounds: the len is 0 but the index is 3
2024-08-27T09:28:36.437463Z ERROR aleo_prover::client: Connection broken: "Stream from prover closed"

**Comment by winca** [comment]
the same problem

**Comment by cgf120** [comment]
the same problem

**Comment by cgf120** [comment]
not support docker
